config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'forecasts/forecasts#search'

  namespace :forecasts do
    get '/search', to: 'forecasts#search'
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/weather/base/forecast.rb
# frozen_string_literal: true

module Weather
  module Base
    class Forecast
      include ActiveModel::API

      attr_accessor :location, :original_location, :current_temp, :timestamp, :timezone,
                    :humidity, :json, :tomorrow, :five_day, :error

      validates :location, :original_location, :current_temp, :timestamp, :timezone,
                :humidity, :json, :tomorrow, :five_day, presence: true

      def initialize(_location)
        raise NotImplementedError, 'Override this constructor with one that takes a String location'
      end

      def search(_client)
        raise NotImplementedError, 'Override this method and pass in an API client implementation of choice'
      end
    end
  end
end

app/models/weather/base/forecast_day.rb
# frozen_string_literal: true

module Weather
  module Base
    class ForecastDay
      include ActiveModel::API

      attr_accessor :high_temp, :low_temp, :temp, :description

      validates :high_temp, :low_temp, :temp, :description, presence: true

      def initialize(_json)
        raise NotImplementedError, 'Override this constructor with one that takes a hash built from JSON data'
      end
    end
  end
end

app/models/weather/visual_crossing/forecast.rb
# frozen_string_literal: true

module Weather
  module VisualCrossing
    class Forecast < Weather::Base::Forecast
      def initialize(location)
        self.original_location = location
      end

      def search(client)
        result = client.call(original_location)

        if result.present?
          self.json = result
          self.location = json[:resolvedAddress]
          self.current_temp = json[:currentConditions][:temp]
          self.humidity = json[:currentConditions][:humidity]
          self.timezone = json[:timezone]
          self.timestamp = DateTime.current.in_time_zone(timezone)
          self.tomorrow = ForecastDay.new(json[:days][0])
          self.five_day = ForecastDay.new(json[:days][4])
        else
          self.error = client.error
        end

        self
      end
    end
  end
end

app/models/weather/visual_crossing/forecast_day.rb
# frozen_string_literal: true

module Weather
  module VisualCrossing
    class ForecastDay < Weather::Base::ForecastDay
      def initialize(day_params)
        self.low_temp = day_params[:tempmin]
        self.high_temp = day_params[:tempmax]
        self.temp = day_params[:temp]
        self.description = day_params[:description]
      end
    end
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/forecasts/forecasts_controller.rb
# frozen_string_literal: true

module Forecasts
  class ForecastsController < ApplicationController
    def search
      return unless params[:location].present?

      @forecast = Rails.cache.fetch(['forecast', params[:location]], expires: 30.minutes) do
        @retrieved = true
        @forecast = Weather::ForecastService.forecast(params[:location])
      end
    end
  end
end

app/helpers/forecasts_helper.rb
# frozen_string_literal: true

module ForecastsHelper
  def format_date_time(date_time)
    date_time.to_formatted_s(:long_ordinal)
  end

  def format_date_time_ago(date_time, start_time = DateTime.current)
    interval = (start_time.to_i - date_time.to_i)
    Time.at(interval).utc.strftime('%M minutes, %S seconds')
  end
end

app/views/forecasts/forecasts/_forecast_day.html.erb
<div class="forecast-search-result-field">
  Average Temperature: <%= day.temp %>
</div>

<div class="forecast-search-result-field">
  Low Temperature: <%= day.low_temp %>
</div>

<div class="forecast-search-result-field">
  High Temperature: <%= day.high_temp %>
</div>

<div class="forecast-search-result-field">
  Description: <%= day.description %>
</div>

app/views/forecasts/forecasts/_search_errors.html.erb
  <h3>Search Error</h3>
  <%= error %>

app/views/forecasts/forecasts/_search_form.html.erb
<%= form_tag forecasts_search_path, method: :get, class: 'forecast-search-form' do %>
  <%= text_field_tag :location, params[:location], placeholder: "ZIP code or address",
                                    autofocus: "autofocus",
                                    class: 'search-input' %>

  <br/>

  <%= submit_tag (params[:location].present? ?  'Search Again!' : "Search!"), name: nil, class: 'search-button' %>
<% end %>

app/views/forecasts/forecasts/_search_heading.html.erb
<% if forecast && forecast.error.blank? %>
  <% content_for :title, "Weather forecast for #{forecast.location}" %>
  <h1>Weather forecast for <%= forecast.location %></h1>
<% else %>
  <% content_for :title, "Search for a weather forecast by location" %>
  <h1>Search for a weather forecast by location</h1>
<% end %>

app/views/forecasts/forecasts/_search_results.html.erb
<div class="forecast-search-results">
  <h2><%= forecast.location %></h2>

  <div class="forecast-search-result-heading">
    <% if retrieved %>
      Forecast freshly retrieved
    <% else %>
      Forecast cached since:
      <br/>
      <%= format_date_time_ago(forecast.timestamp) %> ago
    <% end %>
    at <%= format_date_time(forecast.timestamp) %>
    in the
    <%= forecast.timezone.humanize.titleize %> time zone
  </div>

  <hr/>

  <div class="forecast-search-result-data">
    <h3>Current conditions</h3>
    <div class="forecast-search-result-field">
      Temperature: <%= forecast.current_temp %>&deg; F
      </div>
    <div class="forecast-search-result-field">
      Humidity: <%= forecast.humidity %> %
      </div>
  </div>

  <hr/>
  <div class="forecast-search-result-data">
    <h3>Tomorrow's forecast</h3>
    <%= render "forecast_day", day: forecast.tomorrow %>
  </div>

  <hr/>

  <div class="forecast-search-result-data">
    <h3>5 day forecast</h3>
    <%= render "forecast_day", day: forecast.five_day %>
  </div>
</div>

app/views/forecasts/forecasts/search.html.erb
<%= render 'search_heading', forecast: @forecast %>
<%= render 'search_form' %>

<% if @forecast&.valid? %>
  <%= render 'search_results', forecast: @forecast, retrieved: @retrieved %>
<% elsif @forecast %>
  <%= render 'search_errors', error: @forecast.error %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class='app-container'>
      <%= yield %>
    </div>
  </body>
</html>